# Generated by Django 4.2.23 on 2025-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='stock',
        ),
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(default='furniture_images/chair.jpg', upload_to='furniture_images/'),
            preserve_default=False,
        ),
    ]
